<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/View.php'; require dirname(__DIR__).'/app/Mailer.php';
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH) ?: '/'; $method=$_SERVER['REQUEST_METHOD'];
function form_token(): string { return '<input type="hidden" name="_token" value="'.e($_SESSION['csrf']).'">'; }
function rate_limited(string $email): bool { $s=db()->prepare('SELECT COUNT(*) FROM login_attempts WHERE email=? AND ip=? AND attempted_at>DATE_SUB(NOW(), INTERVAL '.(int)config('LOGIN_DECAY_MINUTES','15').' MINUTE)'); $s->execute([$email,$_SERVER['REMOTE_ADDR']??'']); return (int)$s->fetchColumn() >= (int)config('LOGIN_MAX_ATTEMPTS','5'); }
function reset_link(string $email): void { $token=bin2hex(random_bytes(32)); db()->beginTransaction(); try { db()->prepare('DELETE FROM password_reset_tokens WHERE email=?')->execute([$email]); db()->prepare('INSERT INTO password_reset_tokens (email,token) VALUES (?,?)')->execute([$email,password_hash($token,PASSWORD_ARGON2ID)]); db()->commit(); send_reset_email($email,$token); log_event('password_reset_requested',['email'=>$email]); } catch(Throwable $e) { if(db()->inTransaction())db()->rollBack(); throw $e; } }
if ($path==='/login' && $method==='GET') { if(current_user()) redirect('/'); render('Sign in','<form method="post"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label>'.form_token().'<button>Sign in</button></form><p><a href="/forgot-password">Forgot password?</a></p>',false); exit; }
if ($path==='/login' && $method==='POST') { csrf(); $email=strtolower(trim($_POST['email']??'')); if(rate_limited($email)) { log_event('login_rate_limited',['email'=>$email]); flash('error','Too many attempts. Try again later.'); redirect('/login'); } if(!attempt_login($email,$_POST['password']??'')) { db()->prepare('INSERT INTO login_attempts (email,ip) VALUES (?,?)')->execute([$email,$_SERVER['REMOTE_ADDR']??'']); log_event('login_failed',['email'=>$email]); flash('error','Invalid email or password.'); redirect('/login'); } db()->prepare('DELETE FROM login_attempts WHERE email=?')->execute([$email]); redirect('/'); }
if ($path==='/logout' && $method==='POST') { csrf(); logout(); session_start(); $_SESSION['csrf']=bin2hex(random_bytes(32)); flash('success','You have been signed out.'); redirect('/login'); }
if ($path==='/forgot-password' && $method==='GET') { render('Reset password','<form method="post"><label>Email<input name="email" type="email" autocomplete="email" required></label>'.form_token().'<button>Send reset link</button></form>',false); exit; }
if ($path==='/forgot-password' && $method==='POST') { csrf(); $email=strtolower(trim($_POST['email']??'')); $s=db()->prepare('SELECT email FROM users WHERE email=? AND status="active"'); $s->execute([$email]); if($s->fetch()) { try { reset_link($email); } catch(Throwable $e) { log_event('password_reset_delivery_failed',['email'=>$email]); } } flash('success','If that email is registered, a reset link has been sent.'); redirect('/forgot-password'); }
if ($path==='/reset-password' && $method==='GET') { $email=$_GET['email']??''; $token=$_GET['token']??''; render('Choose a new password','<form method="post"><input type="hidden" name="email" value="'.e($email).'"><input type="hidden" name="token" value="'.e($token).'"><label>New password<input name="password" type="password" autocomplete="new-password" required></label><label>Confirm new password<input name="confirm_password" type="password" autocomplete="new-password" required></label>'.form_token().'<button>Reset password</button></form>',false); exit; }
if ($path==='/reset-password' && $method==='POST') { csrf(); $email=strtolower(trim($_POST['email']??'')); $token=$_POST['token']??''; $s=db()->prepare('SELECT token,created_at FROM password_reset_tokens WHERE email=?'); $s->execute([$email]); $row=$s->fetch(); $error=valid_password($_POST['password']??'') ?: (($_POST['password']??'')!==($_POST['confirm_password']??'') ? 'Passwords do not match.' : null); if(!$row || strtotime($row['created_at']) < time()-(int)config('PASSWORD_RESET_MINUTES','60')*60 || !password_verify($token,$row['token'])) $error='This reset link is invalid or expired.'; if($error){flash('error',$error);redirect('/reset-password?email='.rawurlencode($email).'&token='.rawurlencode($token));} db()->beginTransaction(); try{db()->prepare('UPDATE users SET password=?,must_change_password=0 WHERE email=?')->execute([password_hash($_POST['password'],PASSWORD_ARGON2ID),$email]);db()->prepare('DELETE FROM password_reset_tokens WHERE email=?')->execute([$email]);db()->commit();log_event('password_reset',['email'=>$email]);}catch(Throwable $e){db()->rollBack();throw $e;} flash('success','Password changed. You can now sign in.');redirect('/login'); }
if ($path==='/register' && $method==='GET') { require_super_admin(); render('Create account','<form method="post"><label>Name<input name="name" maxlength="120"></label><label>Email<input name="email" type="email" required></label><label>Role<select name="role"><option value="admin">Admin</option><option value="super_admin">Super Admin</option></select></label><label>Temporary password<input name="password" type="password" required></label><label>Confirm password<input name="confirm_password" type="password" required></label>'.form_token().'<button>Create account</button></form>'); exit; }
if ($path==='/register' && $method==='POST') { require_super_admin(); csrf(); $email=strtolower(trim($_POST['email']??'')); $error=valid_password($_POST['password']??'') ?: (($_POST['password']??'')!==($_POST['confirm_password']??'')?'Passwords do not match.':null); if(!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Enter a valid email.'; if($error){flash('error',$error);redirect('/register');} try{db()->prepare('INSERT INTO users (name,email,password,role,must_change_password) VALUES (?,?,?,?,1)')->execute([trim($_POST['name']??''),$email,password_hash($_POST['password'],PASSWORD_ARGON2ID),$_POST['role']==='super_admin'?'super_admin':'admin']);log_event('user_created',['email'=>$email]);flash('success','Account created.');}catch(PDOException $e){flash('error','An account with that email already exists.');} redirect('/users'); }
if ($path==='/profile' && $method==='GET') { $u=require_auth(); render('Profile','<div class="card"><p><strong>Name:</strong> '.e($u['name']?:'—').'</p><p><strong>Email:</strong> '.e($u['email']).'</p><p><strong>Role:</strong> '.e(str_replace('_',' ',ucwords($u['role'],'_'))).'</p></div><h3>Account Settings</h3><form method="post" action="/profile/password"><label>Current password<input name="current_password" type="password" required></label><label>New password<input name="password" type="password" required></label><label>Confirm new password<input name="confirm_password" type="password" required></label>'.form_token().'<button>Change password</button></form>'); exit; }
if ($path==='/profile/password' && $method==='POST') { $u=require_auth(); csrf(); $s=db()->prepare('SELECT password FROM users WHERE id=?');$s->execute([$u['id']]);$old=$s->fetchColumn(); $error=null; if(!password_verify($_POST['current_password']??'',$old)) $error='Current password is incorrect.'; elseif($error=valid_password($_POST['password']??'')) {} elseif(($_POST['password']??'')!==($_POST['confirm_password']??'')) $error='Passwords do not match.'; elseif(password_verify($_POST['password'],$old)) $error='New password must differ from current password.'; if($error){flash('error',$error);redirect('/profile');} db()->prepare('UPDATE users SET password=?,must_change_password=0 WHERE id=?')->execute([password_hash($_POST['password'],PASSWORD_ARGON2ID),$u['id']]);session_regenerate_id(true);log_event('password_changed',['user_id'=>$u['id']]);flash('success','Password changed.');redirect('/profile'); }
if ($path==='/users' && $method==='GET') { require_super_admin(); $users=db()->query('SELECT id,name,email,role,status,created_at,last_login_at FROM users ORDER BY created_at DESC')->fetchAll(); $rows='';foreach($users as $u){$rows.='<tr><td>'.e($u['name']).'</td><td>'.e($u['email']).'</td><td>'.e($u['role']).'</td><td>'.e($u['status']).'</td><td>'.e($u['created_at']).'</td><td>'.e($u['last_login_at']?:'—').'</td><td><form method="post" action="/users/reset" style="margin:0">'.form_token().'<input type="hidden" name="email" value="'.e($u['email']).'"><button>Send Password Reset Link</button></form><form method="post" action="/users/password" style="margin:0"><input type="hidden" name="id" value="'.e((string)$u['id']).'">'.form_token().'<input name="password" type="password" placeholder="New password" required><input name="confirm_password" type="password" placeholder="Confirm password" required><button>Set password</button></form><form method="post" action="/users/role" style="margin:0"><input type="hidden" name="id" value="'.e((string)$u['id']).'">'.form_token().'<select name="role"><option value="admin"'.($u['role']==='admin'?' selected':'').'>Admin</option><option value="super_admin"'.($u['role']==='super_admin'?' selected':'').'>Super Admin</option></select><button>Update role</button></form></td></tr>'; } render('User Management','<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Last login</th><th>Action</th></tr></thead><tbody>'.$rows.'</tbody></table>');exit; }
if ($path==='/users/password' && $method==='POST') { $actor=require_super_admin();csrf();$id=(int)($_POST['id']??0);$error=valid_password($_POST['password']??'') ?: (($_POST['password']??'')!==($_POST['confirm_password']??'')?'Passwords do not match.':null);if(!$id)$error='Invalid user.';if($error){flash('error',$error);redirect('/users');}db()->prepare('UPDATE users SET password=?,must_change_password=1 WHERE id=?')->execute([password_hash($_POST['password'],PASSWORD_ARGON2ID),$id]);log_event('admin_password_changed',['actor_id'=>$actor['id'],'user_id'=>$id]);flash('success','User password updated. They must change it after signing in.');redirect('/users'); }
if ($path==='/users/role' && $method==='POST') { $actor=require_super_admin();csrf();$id=(int)($_POST['id']??0);$role=$_POST['role']==='super_admin'?'super_admin':'admin';if($id===$actor['id'] && $role!=='super_admin'){flash('error','You cannot remove your own Super Admin access.');redirect('/users');}db()->prepare('UPDATE users SET role=? WHERE id=?')->execute([$role,$id]);log_event('user_role_changed',['actor_id'=>$actor['id'],'user_id'=>$id,'role'=>$role]);flash('success','User role updated.');redirect('/users'); }
if ($path==='/users/reset' && $method==='POST') { require_super_admin();csrf();$email=strtolower(trim($_POST['email']??''));$s=db()->prepare('SELECT email FROM users WHERE email=?');$s->execute([$email]);if($s->fetch()){try{reset_link($email);flash('success','Password reset link sent.');}catch(Throwable $e){flash('error','Could not send reset email. Check mail configuration.');}}redirect('/users'); }
if (in_array($path,['/','/resources','/calendar','/trainings','/guidelines','/weekly-releases','/static-1','/static-2'],true)) { $u=require_auth(); if($path==='/') render('Homepage','<div class="card"><a class="button" href="/resources">Material / Resources Request</a> <a class="button" href="/calendar">View Calendar</a> <a class="button" href="/resources">Browse Resources</a></div><div class="card"><h3>Upcoming events</h3><p>0 upcoming events</p></div><div class="card"><h3>This week</h3><p>No events scheduled. <a href="/calendar">View full calendar</a></p></div><div class="card"><h3>Quick links</h3><p>Resources, trainings, and guidelines are ready for future milestones.</p></div>'); else render(ucwords(trim(str_replace('-',' ',$path),'/')),'<div class="card"><p>This protected section is ready for the next milestone.</p></div>'); exit; }
http_response_code(404); render('Not found','<p>The requested page does not exist.</p>',false);
