<?php declare(strict_types=1);
require_once dirname(__DIR__).'/View.php';require_once dirname(__DIR__).'/Models/SFlexPost.php';require_once dirname(__DIR__).'/Models/UploadJob.php';
final class SFlexController{
private function json(array $d,int $s=200):void{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE);}
private function fail(bool $async,int $job,int $user,string $msg):void{if($job)UploadJob::fail($job,$user,$msg);if($async){$this->json(['error'=>$msg],422);return;}flash('error',$msg);redirect('/sflex/create');}
private function files():array{$f=$_FILES['media']??null;if(!$f)return[];if(!is_array($f['name']))return[ $f ];$out=[];foreach($f['name']as$i=>$name)$out[]=['name'=>$name,'type'=>$f['type'][$i],'tmp_name'=>$f['tmp_name'][$i],'error'=>$f['error'][$i],'size'=>$f['size'][$i]];return$out;}
public function create():void{$u=require_auth();csrf();$async=($_POST['ajax']??'')==='1';$job=(int)($_POST['upload_job_id']??0);$caption=trim((string)($_POST['caption']??''));$files=$this->files();if($caption===''&&!$files){$this->fail($async,$job,(int)$u['id'],'Add a caption or media.');return;}if(count($files)>10){$this->fail($async,$job,(int)$u['id'],'A post can contain up to 10 images.');return;}$media=[];foreach($files as$f){if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||(int)$f['size']>4*1024*1024*1024){$this->fail($async,$job,(int)$u['id'],'The media upload failed or is larger than 4 GB.');return;}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$type=str_starts_with($mime,'image/')?'image':(str_starts_with($mime,'video/')?'video':null);if(!$type||($type==='video'&&count($files)>1)){$this->fail($async,$job,(int)$u['id'],'Use valid images, or a single video.');return;}$folder='sflex/'.$type.'/'.date('Y-m-d');$dir=dirname(__DIR__,2).'/storage/'.$folder;if(!is_dir($dir))mkdir($dir,0700,true);$name=bin2hex(random_bytes(16)).($type==='image'?'.jpg':'.mp4');if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name)){$this->fail($async,$job,(int)$u['id'],'Media could not be stored.');return;}$media[]=['path'=>$folder.'/'.$name,'type'=>$type];}
$first=$media[0]??null;$post=SFlexPost::create((int)$u['id'],$caption,$first['path']??null,$first['type']??null,$u['role']==='super_admin'?'approved':'pending');if($media)SFlexPost::addMedia($post,$media);if($job)UploadJob::complete($job,(int)$u['id'],'sflex',$post);$message=$u['role']==='super_admin'?'Post published.':'Post sent for approval.';if($async){$this->json(['ok'=>true,'message'=>$message,'link'=>'/sflex/post/'.$post]);return;}flash('success',$message);redirect('/sflex');}
public function media(array $p):void{require_auth();foreach($p as$v)if(basename($v)!==$v){http_response_code(404);return;}$f=realpath(dirname(__DIR__,2).'/storage/sflex/'.$p['type'].'/'.$p['date'].'/'.$p['file']);if(!$f||!is_file($f)){http_response_code(404);return;}header('Content-Type: '.(new finfo(FILEINFO_MIME_TYPE))->file($f));readfile($f);}
public function react(array $p):void{$u=require_auth();csrf();$r=(string)($_POST['reaction']??'');if(!in_array($r,['like','heart','smile','laugh','cry'],true)){$this->json(['error'=>'Invalid reaction.'],422);return;}SFlexPost::react((int)$p['id'],(int)$u['id'],$r);$this->json(['ok'=>true]);}
public function reactions(array $p):void{require_auth();$this->json(['reactions'=>SFlexPost::reactionUsers((int)$p['id'])]);}
public function comments(array $p):void{$u=require_auth();$this->json(['comments'=>SFlexPost::comments((int)$p['id'],$u['role']==='super_admin')]);}
public function comment(array $p):void{$u=require_auth();csrf();$body=trim((string)($_POST['body']??''));$async=($_POST['ajax']??'')==='1';if($body===''||mb_strlen($body)>1000){if($async)$this->json(['error'=>'Comments must be between 1 and 1000 characters.'],422);else{flash('error','Comments must be between 1 and 1000 characters.');redirect('/sflex');}return;}$parent=(int)($_POST['parent_id']??0);if($parent)$ok=SFlexPost::reply((int)$p['id'],(int)$u['id'],$parent,$body);else{SFlexPost::comment((int)$p['id'],(int)$u['id'],$body);$ok=true;}if($async){$this->json(['ok'=>$ok],$ok?200:422);return;}flash($ok?'success':'error',$ok?'Comment added.':'Reply could not be added.');redirect('/sflex');}
public function deleteComment(array $p):void{$u=require_auth();csrf();$ok=SFlexPost::deleteComment((int)$p['id'],(int)$u['id'],$u['role']==='super_admin');$this->json(['ok'=>$ok],$ok?200:403);}
public function moderateComment(array $p):void{require_super_admin();csrf();$a=(string)($_POST['action']??'');if(!in_array($a,['hide','unhide','remove'],true)){$this->json(['error'=>'Invalid action.'],422);return;}SFlexPost::moderateComment((int)$p['id'],$a);$this->json(['ok'=>true]);}
public function review(array $p):void{require_super_admin();csrf();SFlexPost::review((int)$p['id'],($_POST['status']??'')==='approved'?'approved':'rejected');redirect('/sflex/review');}
}
