<?php declare(strict_types=1);
final class SFlexPost { private static function select():string{return "SELECT p.*,u.name author,(SELECT COUNT(*) FROM sflex_comments c WHERE c.post_id=p.id AND c.hidden_at IS NULL) comments,(SELECT reaction FROM sflex_reactions r WHERE r.post_id=p.id AND r.user_id=?) mine FROM sflex_posts p JOIN users u ON u.id=p.user_id";}
 public static function feed(int $user,int $offset):array{$s=db()->prepare(self::select()." WHERE p.status='approved' ORDER BY p.created_at DESC LIMIT 5 OFFSET ?");$s->bindValue(1,$user,PDO::PARAM_INT);$s->bindValue(2,$offset,PDO::PARAM_INT);$s->execute();$rows=$s->fetchAll();foreach($rows as&$r){$q=db()->prepare('SELECT reaction,COUNT(*) total FROM sflex_reactions WHERE post_id=? GROUP BY reaction');$q->execute([$r['id']]);$r['counts']=$q->fetchAll();}return $rows;}
 public static function create(int $user,string $caption,?string $path,?string $type,string $status):void{db()->prepare('INSERT INTO sflex_posts(user_id,caption,media_path,media_type,status) VALUES(?,?,?,?,?)')->execute([$user,$caption,$path,$type,$status]);}
 public static function react(int $post,int $user,string $reaction):void{$s=db()->prepare('SELECT reaction FROM sflex_reactions WHERE post_id=? AND user_id=?');$s->execute([$post,$user]);if($s->fetchColumn()===$reaction){db()->prepare('DELETE FROM sflex_reactions WHERE post_id=? AND user_id=?')->execute([$post,$user]);return;}db()->prepare('INSERT INTO sflex_reactions(post_id,user_id,reaction) VALUES(?,?,?) ON DUPLICATE KEY UPDATE reaction=VALUES(reaction),created_at=NOW()')->execute([$post,$user,$reaction]);}
 public static function comments(int $post,bool $admin):array{$q='SELECT c.*,u.name author FROM sflex_comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=?'.($admin?'':' AND c.hidden_at IS NULL').' ORDER BY c.created_at ASC';$s=db()->prepare($q);$s->execute([$post]);return $s->fetchAll();}
 public static function comment(int $post,int $user,string $body):void{db()->prepare('INSERT INTO sflex_comments(post_id,user_id,body) VALUES(?,?,?)')->execute([$post,$user,$body]);}
 public static function review(int $id,string $status):void{db()->prepare('UPDATE sflex_posts SET status=? WHERE id=?')->execute([$status,$id]);}
 public static function pending():array{return db()->query("SELECT p.*,u.name author FROM sflex_posts p JOIN users u ON u.id=p.user_id WHERE p.status='pending' ORDER BY p.created_at")->fetchAll();}
}
